version: "3"
services:

    konlper:
      image: 210.123.23.82:7000/gate
      ports: 
        - "80:5000"
      deploy:
        replicas: 1
        update_config:
          parallelism: 2
          delay: 10m
        restart_policy:
          condition: on-failure
        placement:
          constraints: [node.role == manager]
